---
# tasks file for hyperpc-nginx-role
- name: Install_nginx
  ansible.builtin.apt:
    name: nginx
    state: present

- name: Ensure_nginx_config_directory_exists
  ansible.builtin.file:
    path: "{{ hyperpc_nginx_role_config_path | dirname }}"
    state: directory
    mode: "0755"

- name: Create_nginx_proxy_config
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: "{{ hyperpc_nginx_role_config_path }}"
    owner: root
    group: root
    mode: "0644"
    backup: true
  notify: "reload nginx safely"

- name: Start_nginx_unit
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
