---
# tasks file for hyperpc-nginx-role
- name: Ensure_nginx_config_directory_exists
  ansible.builtin.file:
    path: "{{ nginx_config_path | dirname }}"
    state: directory
    mode: "0755"

- name: Check_if_nginx_config_exists
  ansible.builtin.stat:
    path: "{{ hyperpc_nginx_role_config_path }}"
  register: hyperpc_nginx_role_nginx_conf_stat

- name: Backup existing nginx config
  ansible.builtin.copy:
    src: "{{ nginx_config_path }}"
    dest: "{{ nginx_config_path }}.bak"
    remote_src: true
    owner: root
    group: root
    mode: "0644"
  when: hyperpc_nginx_role_nginx_conf_stat.stat.exists

- name: Create_nginx_proxy_config
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: "{{ nginx_config_path }}"
    owner: root
    group: root
    mode: "0644"
  notify: "reload nginx safely"

- name: Start_nginx_unit
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
