name: Ansible_lint_and_deploy

on:
  push:
    branches: [ main, "feature/**" ]
  pull_request:
    branches: 
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout_repository
        uses: actions/checkout@v4

      - name: Set_up_Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install_ansible-lint
        run: |
          pip install --upgrade pip
          pip install ansible ansible-lint

      - name: Run_ansible-lint
        run: |
          ansible-lint roles/hyperpc_nginx_role

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install ansible
        run: |
          pip install --upgrade pip
          pip install ansible ansible-lint

      - name: Save SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Run Ansible
        run: ansible-playbook -i inventory.yaml site.yml