name: Ansible_Lint

on:
  push:
    branches: [ main, "feature/**" ]
  pull_request:
    branches: 
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout_repository
        uses: actions/checkout@v4

      - name: Set_up_Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install_ansible-lint
        run: |
          pip install --upgrade pip
          pip install ansible ansible-lint

      - name: Run_ansible-lint
        run: |
          ansible-lint roles/hyperpc_nginx_role
